version: '3.9'

services:
  app:
    image: ruby
    volumes:
      - ./:/app
      - rubygems:/usr/local/bundle
    working_dir: /app
    ports:
      - "3000:3000"
    networks:
      - test

  redis:
    image: redis
    networks:
      - test

  postgres:
    image: postgres
    restart: always
    ports:
      - "7777:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    command: [
      "postgres",
      "-c",
      "max_wal_size=2GB",
      "-c",
      "min_wal_size=80MB"
    ]
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - test

volumes:
  rubygems:
  pgdata:

networks:
  test:
