version: '3.9'

services:
  ruby:
    image: ruby
    volumes:
      - ./:/app
      - rubygems:/usr/local/bundle
    working_dir: /app
    ports:
      - "3000:3000"
    hostname: ruby
    networks:
      - test

  nodejs:
    image: node
    volumes:
      - ./:/app
      - yarn_cache:/usr/local/share/.cache/yarn/v6
      - node_modules_cache:/app/node_modules
    working_dir: /app
    ports:
      - "4000:4000"
    hostname: nodejs
    networks:
      - test

  redis:
    image: redis
    networks:
      - test

  postgres:
    image: postgres
    restart: always
    ports:
      - "7777:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    command: [
      "postgres",
      "-c",
      "max_wal_size=2GB",
      "-c",
      "min_wal_size=80MB"
    ]
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - test

volumes:
  rubygems:
  pgdata:
  yarn_cache:
  node_modules_cache:

networks:
  test:
