source 'https://rubygems.org'

gem 'sidekiq'
gem 'async-io'
gem 'async-http'
gem 'redis'
gem 'pg', git: 'https://github.com/ged/ruby-pg', branch: 'master'
gem 'faker'
gem 'celluloid'
gem 'byebug'
gem 'typhoeus'
